baseurl = "https://telisar.evilchi.li/"
title = "Noobhammer!"
copyright = "As Syf Tells It in 3207 M.E."
canonifyurls = true

paginate = 30

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "evilchili"
    twitter = "evilchili"
    github = ""
    mastodon = "https://mastodon.social/@evilchili"

[params]
    tagline = "The ongoing adventures of a group of new D&D players in their first game"

[menu]

  [[menu.main]]
    identifier = "sessions"
    name = "Sessions"
    title = "Session Summaries"
    url = "/tags/session/"
    weight = 80

  [[menu.main]]
    identifier = "lore"
    name = "Lore"
    title = "Lore"
    url = "/tags/lore/"
    weight = 90

  [[menu.main]]
    identifier = "bestiary"
    name = "Bestiary"
    title = "Bestiary"
    url = "/tags/monster/"
    weight = 95


  [[menu.main]]
    identifier = "maps"
    name = "Maps"
    title = "Maps and Imagery"
    url = "/maps/"
    weight = 90


  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    title = "Tags"
    url = "/tags/"
    weight = 100

  [[menu.main]]
    identifier = "posts"
    name = "All Posts"
    title = "All Posts"
    url = "/posts/"
    weight = 100


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
