#  name: git-gateway
#  branch: master # Branch to update (optional; defaults to master)
#  #api_root: https://api.github.com
#  #base_url: https://api.netlify.com
#  #auth_endpoint: auth
#  site_domain: localhost:1313

backend:
  name: github
  repo: evilchili/telisar-website


# These lines should *not* be indented
media_folder: "static/static" # Media files will be stored in the repo under static/images/uploads
public_folder: "/static" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "."
    label: "Top-Level Content"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - { label: 'Description', name: 'description', widget: 'string' }
      - {label: "Campaign Date", name: "campaigndate", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Markup", name: "markup", widget: "string"}

  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: 'Description', name: 'description', widget: 'text' }
      - {label: "Campaign Date", name: "campaigndate", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Markup", name: "markup", widget: "string"}

  - name: "bestiary"
    label: "Bestiary"
    folder: "content/beastiary"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: 'Description', name: 'description', widget: 'text' }
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Markup", name: "markup", widget: "string"}
      - label: Stat Block
        name: statblock
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Name2", name: "name2", widget: "string"}
